library(collapsibleTree)
library(data.tree)

tc <- rev(brewer.pal(4, "PuOr"))



const <- Node$new("Constant tempo", fill=tc[1])
  cu <- const$AddChild("Speed up", fill=tc[2])
    cuu <- cu$AddChild("Speed up", fill=tc[2])
      cuuu <- cuu$AddChild("Speed up", fill=tc[2])
      cuud <- cuu$AddChild("Slow down", fill=tc[3])
      cuuc <- cuu$AddChild("Constant tempo", fill=tc[1])
  cd <- const$AddChild("Slow down", fill=tc[3])
    cdd <- cd$AddChild("Slow down", fill=tc[3])
      cddd <- cdd$AddChild("Slow down", fill=tc[3])
      cddu <- cdd$AddChild("Speed up", fill=tc[2])
      cddc <- cdd$AddChild("Constant tempo", fill=tc[1])
  cc <- const$AddChild("Constant tempo", fill=tc[1])
    ccc <- cc$AddChild("Constant tempo", fill=tc[1])
      cccs <- ccc$AddChild("Stress", fill=tc[4])
      cccc <- ccc$AddChild("Constant tempo", fill=tc[1])
      cccd <- ccc$AddChild("Slow down", fill=tc[3])
      cccu <- ccc$AddChild("Speed up", fill=tc[2])
    ccd <- cc$AddChild("Slow down", fill=tc[3])
      ccdd <- ccd$AddChild("Slow down", fill=tc[3])
    ccu <- cc$AddChild("Speed up", fill=tc[2])
      ccuu <- ccu$AddChild("Speed up", fill=tc[2])
    ccs <- cc$AddChild("Stress", fill=tc[4])
      ccsc <- ccs$AddChild("Constant tempo", fill=tc[1])
  cs <- const$AddChild("Stress", fill=tc[4])
    csc <- cs$AddChild("Constant tempo", fill=tc[1])
      cscs <- csc$AddChild("Stress", fill=tc[4])
      cscc <- csc$AddChild("Constant tempo", fill=tc[1])
      cscu <- csc$AddChild("Speed up", fill=tc[2])
      cscd <- csc$AddChild("Slow down", fill=tc[3])
      